import clsx from "clsx"
import type { Metadata } from "next"
import { Raleway } from "next/font/google"
import localFont from "next/font/local"
import { PropsWithChildren } from "react"
import "./globals.css"

export const metadata: Metadata = {
  title: "Дружба",
  description: "Generated by create next app",
}

const ralewayFont = Raleway({
  subsets: ["latin", "cyrillic"],
  variable: "--font-main",
})

const nauruzRedKedsFont = localFont({
  src: "../fonts/nauryz-red-keds.ttf",
  variable: "--font-headline",
})

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="ru">
      <body
        className={clsx(
          ralewayFont.variable,
          nauruzRedKedsFont.variable,
          "font-main"
        )}
      >
        {children}
      </body>
    </html>
  )
}

export default RootLayout
