import { Header } from "@/components"
import { Footer } from "@/components/Footer"
import { manropeFont, nauruzRedKedsFont, ralewayFont } from "@/fonts"
import clsx from "clsx"
import type { Metadata } from "next"
import { PropsWithChildren } from "react"
import "./globals.css"

export const metadata: Metadata = {
  title: "Дружба",
  description: "Generated by create next app",
}

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="ru">
      <body
        className={clsx(
          ralewayFont.variable,
          nauruzRedKedsFont.variable,
          manropeFont.variable,
          "font-main"
        )}
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}

export default RootLayout
